export const FETCH_PASSENGERS_REQUEST = 'FETCH_PASSENGERS_REQUEST';
export const FETCH_PASSENGERS_SUCCESS = 'FETCH_PASSENGERS_SUCCESS';
export const FETCH_PASSENGERS_FAIL = 'FETCH_PASSENGERS_FAIL';

export const CREATE_PASSENGERS_REQUEST = 'CREATE_PASSENGERS_REQUEST';
export const CREATE_PASSENGERS_SUCCESS = 'CREATE_PASSENGERS_SUCCESS';
export const CREATE_PASSENGERS_FAIL = 'CREATE_PASSENGERS_FAIL';

export const UPDATE_PASSENGERS_REQUEST = 'UPDATE_PASSENGERS_REQUEST';
export const UPDATE_PASSENGERS_SUCCESS = 'UPDATE_PASSENGERS_SUCCESS';
export const UPDATE_PASSENGERS_FAIL = 'UPDATE_PASSENGERS_FAIL';